name: project_kisan
description: "A new Flutter project."
publish_to: 'none' # Prevent publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_tts: ^4.0.2
  speech_to_text: ^7.1.0
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  easy_localization: ^3.0.3
  lottie: ^3.1.0
  xml: ^6.5.0
  url_launcher: ^6.2.5
  flutter_typeahead: ^4.8.0
  geolocator: ^9.0.2
  intl: ^0.19.0
  flutter_keyboard_visibility:
    path: plugins/flutter_keyboard_visibility/flutter_keyboard_visibility
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - lib/l10n/
    - assets/lottie/voice_wave.json
    - assets/images/leaf_bg.jpg

dependency_overrides:
  flutter_keyboard_visibility:
    path: plugins/flutter_keyboard_visibility/flutter_keyboard_visibility
